### ISSUE TITLE
parse <ele/> throw exception

### ISSUE THREAD

**Issue by yhonet** [ticofab/android-gpx-parser#1] opened 2016-06-01 10:20 UTC
When there's a "&lt;ele/&gt;" in gpx file, it throw a exception:
GPXParse.readElevation(XmlPullParser parser): line 160
Double ele = Double.valueOf(readText(parser));

I try to fix it:
        final String text = readText(parser);
        Double ele;
        if (TextUtils.isEmpty(text))
        {
            ele = 0d;
        }
        else
        {
            ele = Double.valueOf(text);
        }
but another exception throw from GPXParse.readTime(XmlPullParser parser), and I can't  catch it.

**Comment by ticofab** [comment] 2016-06-02 17:42
Hi @yhonet, and thanks for opening this issue! Can you send me an example route that makes it crash so to help me reproduce it?

**Comment by ticofab** [comment] 2016-06-26 19:02
Closing as I cannot reproduce it.

**Closed by ticofab** 2016-06-26 19:02 UTC
Labels: bug
